# .travis.yml
#
# https://docs.travis-ci.com/user/languages/r/


language: r
sudo: false
warnings_are_errors: false
cache: packages

r_packages:
  - R6
  - plot3D
  - devtools
  - covr
  
after_success:
  - Rscript -e 'library(covr);codecov()'