language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
  - R6
  - plot3D
  - devtools
  - covr

r_github_packages:
  - gabrielpreda/mesh2D

after_success:
  - Rscript -e 'library(covr);codecov()'